name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: npm test

    # # Operating system to run job on
    # runs-on: ubuntu-latest
    # # Steps in job
    # steps:
    #   # Get code from repo
    #   - name: Checkout code
    #     uses: actions/checkout@v1
    #   # Install NodeJS
    #   - name: Use Node.js 12.x
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: 12.x
    #   # Build the app using cypress
    #   - name: Run tests
    #     uses: cypress-io/github-action@v1
    #     with:
    #       build: npm run build
    #       start: npm start
    #       wait-on: http://localhost:3000
    #       browser: chrome